language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-boardweb *
  - mkdir -p deploy
  - mv springboot-boardweb.zip deploy/springboot-boardweb.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 설정 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings 설정 값

    bucket: boardweb-springboot-build #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
      access_key_id: $AWS_ACCESS_KEY # Travis repo settings 설정 값
      secret_access_key: $AWS_SECRET_KEY # Travis repo settings 설정 값

      bucket: boardweb-springboot-build #S3 버킷
      key: springboot-boardweb.zip # 빌드 파일 압축해서 전달
      bundle_type: zip
      application: springboot-boardweb # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
      deployment_group: springboot-boardweb-group # 웹 콘솔에서 등록한 CodeDeploy 배포그룹
      region: ap-northeast-2
      wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sge7102@skuniv.ac.kr


